
name: Generate docs

on:
  release:
    types:
      - created

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        env:
          NODE_ENV: development
      - run: npm run generate-docs
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: docs
          folder: docs
